# Numpy Basic functions !

In [1]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])
print(arr)
print(type(arr))

[1 2 3 4 5 6 7 8]
<class 'numpy.ndarray'>


In [2]:
arr1=np.array([[1,2,3,4],[5,6,7,8]],dtype='int64')
print(arr1)
arr1.shape
arr1.dtype

[[1 2 3 4]
 [5 6 7 8]]


dtype('int64')

# operations on 2 numpy array (operation on elements !)


In [3]:
arr2=np.array([[1,2,3,4],[1,4,5,6]],dtype='int64')
a=arr1*arr2
print(a)
b=arr1+arr2
print(b)
c=arr1-arr2
print(c)
d=arr1/arr2
print(d)

[[ 1  4  9 16]
 [ 5 24 35 48]]
[[ 2  4  6  8]
 [ 6 10 12 14]]
[[0 0 0 0]
 [4 2 2 2]]
[[1.         1.         1.         1.        ]
 [5.         1.5        1.4        1.33333333]]


# slicing !


In [4]:
arr3=np.array([1,2,3,4,5,6])
e=arr3[3:5]
print(e)
e[0]=5
print(e)
print(arr3)

[4 5]
[5 5]
[1 2 3 5 5 6]


# some important functions !


In [5]:
print(arr1)
f=arr1.sum(axis=0) # axis =0 is vertical which means for columns
g=arr1.sum(axis=1) # axis =1 is horizontal which means for rows
print(f,g)

[[1 2 3 4]
 [5 6 7 8]]
[ 6  8 10 12] [10 26]


# cross and dot product !


In [6]:
print(arr1)
print(arr2)
np.dot(arr1,arr2.transpose()) #if same dimension perform transpose of matrix

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [1 4 5 6]]


array([[ 30,  48],
       [ 70, 112]], dtype=int64)

In [7]:
arra1=np.array([[1,2,3],[5,6,7]])
arra2=np.array([[0,9,8],[3,4,5]])
np.cross(arra1,arra2)

array([[-11,  -8,   9],
       [  2,  -4,   2]])

# sorting !

In [8]:
arra3=np.array([[9,8,5,4],[7,6,7,6]])
print(arra3)
v=np.sort(arra3,axis=0,kind='quicksort') #sorted by columns as axis= 0 , kind is used to select any alogrithm for sorting
u=np.sort(arra3,axis=1,kind='mergesort') #sorted by rows as axis = 1 
print(v)
print(u)

[[9 8 5 4]
 [7 6 7 6]]
[[7 6 5 4]
 [9 8 7 6]]
[[4 5 8 9]
 [6 6 7 7]]


# some more functions in numpy !

In [9]:
arra4=np.arange(8)
print(arra4)
m=arra4.reshape(2,4)
n=arra4.reshape(4,2)
print(m)
print(n)

[0 1 2 3 4 5 6 7]
[[0 1 2 3]
 [4 5 6 7]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [10]:
arra5=np.array([2,4,6,1,2,9,7,5,9,3,4,2,1,7,8,9,10])
np.argsort(arra5)


array([ 3, 12,  0,  4, 11,  9,  1, 10,  7,  2,  6, 13, 14,  8,  5, 15, 16],
      dtype=int64)

In [11]:
np.argmin(b)

0

In [12]:
np.argmax(b)

7